000

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!unzip /content/drive/MyDrive/kaggle_datasets/home-data-for-ml-course.zip

Archive:  /content/drive/MyDrive/kaggle_datasets/home-data-for-ml-course.zip
  inflating: data_description.txt
  inflating: sample_submission.csv
  inflating: sample_submission.csv.gz
  inflating: test.csv
  inflating: test.csv.gz
  inflating: train.csv
  inflating: train.csv.gz

In [ ]:
dataset = pd.read_csv('/content/train.csv', index_col='Id')

In [ ]:
dataset.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
dataset.select_dtypes('object').nunique().sort_values()

Street            2
Alley             2
Utilities         2
CentralAir        2
MasVnrType        3
LandSlope         3
PavedDrive        3
GarageFinish      3
PoolQC            3
ExterQual         4
BsmtQual          4
BsmtExposure      4
BsmtCond          4
KitchenQual       4
LandContour       4
LotShape          4
Fence             4
MiscFeature       4
ExterCond         5
Electrical        5
HeatingQC         5
BldgType          5
MSZoning          5
LotConfig         5
GarageQual        5
GarageCond        5
FireplaceQu       5
Heating           6
BsmtFinType1      6
BsmtFinType2      6
RoofStyle         6
Foundation        6
GarageType        6
SaleCondition     6
Functional        7
HouseStyle        8
RoofMatl          8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [ ]:
processed = dataset.dropna(axis=1).select_dtypes(exclude='object')

In [ ]:
processed.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,8450,7,5,2003,2003,706,0,150,856,...,0,61,0,0,0,0,0,2,2008,208500
2,20,9600,6,8,1976,1976,978,0,284,1262,...,298,0,0,0,0,0,0,5,2007,181500
3,60,11250,7,5,2001,2002,486,0,434,920,...,0,42,0,0,0,0,0,9,2008,223500
4,70,9550,7,5,1915,1970,216,0,540,756,...,0,35,272,0,0,0,0,2,2006,140000
5,60,14260,8,5,2000,2000,655,0,490,1145,...,192,84,0,0,0,0,0,12,2008,250000

In [ ]:
processed.shape

(1460, 34)

In [ ]:
corr_list = processed.corr()['SalePrice'].sort_values(ascending=False)
# print(corr_list)

In [ ]:
corr_features = list(corr_list[1:10].index)
print(corr_features)
kaggle_features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt']

In [ ]:
# X = processed[corr_features]
X = dataset[corr_features]
# X = dataset[kaggle_features]
y = dataset.SalePrice
# X = processed[kaggle_features]
# y = processed.SalePrice

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=1)

In [ ]:
dataset.shape

(1460, 80)

In [ ]:
X_train.shape

(1095, 9)

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

# model = keras.Sequential([
#     layers.Dense(512, activation='relu', input_shape=[9]),
#     layers.Dropout(0.3),
#     layers.BatchNormalization(),
#     layers.Dense(512, activation='relu'),
#     layers.Dropout(0.3),
#     layers.BatchNormalization(),
#     layers.Dense(512, activation='relu'),
#     layers.Dropout(0.3),
#     layers.BatchNormalization(),
#     layers.Dense(1),
# ])
model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=[9]),
    layers.Dropout(0.3),
    layers.BatchNormalization(),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),
    layers.BatchNormalization(),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),
    layers.BatchNormalization(),
    layers.Dense(1),
])
# model = keras.Sequential([
#     layers.Dense(512, activation='relu', input_shape=[9]),
#     layers.Dense(512, activation='relu'),
#     layers.Dense(512, activation='relu'),
#     layers.Dense(1),
# ])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
from tensorflow.keras.optimizers import Adam

In [ ]:
model.compile(
    optimizer=Adam(learning_rate=0.4),
    # optimizer='adam',
    loss='mae',
)

In [ ]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_valid, y_valid),
    batch_size=128,
    epochs=100,
    # batch_size=256,
    # epochs=10,
)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 33351.3984 - val_loss: 36980.3359
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 34367.7891 - val_loss: 31507.6387
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 34614.3398 - val_loss: 30749.7559
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32624.7832 - val_loss: 37321.1406
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32161.6328 - val_loss: 33217.4258
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33029.7461 - val_loss: 36769.8047
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32244.8535 - val_loss: 34865.9492
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32675.1660 - val_loss: 32704.6523
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32216.7852 - val_loss: 35713.5508
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32660.4414 - val_loss: 33627.1250
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32224.3398 - val_loss: 34673.4219
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33189.8281 - val_loss: 35874.9219
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 37015.8633 - val_loss: 38515.7031
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 33731.4570 - val_loss: 35212.9648
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32705.1953 - val_loss: 35218.9531
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30711.9551 - val_loss: 37914.0156
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 33189.0312 - val_loss: 36796.9102
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32030.6543 - val_loss: 31644.8555
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31625.1094 - val_loss: 31992.1953
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31948.7227 - val_loss: 33395.7539
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 31174.0625 - val_loss: 34141.6836
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31706.3633 - val_loss: 38055.4531
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31775.6230 - val_loss: 34049.1562
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30356.9531 - val_loss: 33367.1914
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31601.5391 - val_loss: 33795.9844
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32266.1367 - val_loss: 33154.2031
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29985.9844 - val_loss: 36175.1523
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32517.5508 - val_loss: 34417.5234
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32806.5664 - val_loss: 34476.8477
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30166.4648 - val_loss: 37061.4102
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30399.6621 - val_loss: 32302.3926
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32245.8203 - val_loss: 31740.2656
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30727.4570 - val_loss: 35465.8672
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 30953.6211 - val_loss: 33211.7539
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31134.3535 - val_loss: 34636.9297
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32871.8203 - val_loss: 33643.1250
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32468.8965 - val_loss: 36439.9258
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32539.8984 - val_loss: 33208.7891
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33383.4102 - val_loss: 32245.5078
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32278.8652 - val_loss: 34020.1133
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31159.5527 - val_loss: 32821.1406
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31676.3750 - val_loss: 35788.8750
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32177.8379 - val_loss: 34414.9023
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31190.2402 - val_loss: 37423.4141
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31652.7012 - val_loss: 35100.5430
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30740.7676 - val_loss: 33764.9961
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31430.4219 - val_loss: 27862.9941
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32667.8066 - val_loss: 42564.7305
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31338.1934 - val_loss: 40364.0234
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29437.3535 - val_loss: 35659.9766
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31139.6699 - val_loss: 37531.1055
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32103.0215 - val_loss: 36791.4727
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 31558.0156 - val_loss: 36522.6875
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33112.5977 - val_loss: 33571.4102
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31696.2871 - val_loss: 34759.2461
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32655.3828 - val_loss: 38113.7930
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29764.1152 - val_loss: 38237.5469
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30733.8281 - val_loss: 39002.0703
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31290.5293 - val_loss: 35508.6680
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30381.5078 - val_loss: 34409.2617
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 30511.1250 - val_loss: 34314.4648
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30680.5586 - val_loss: 35065.2852
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31050.1191 - val_loss: 36885.3008
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32009.7266 - val_loss: 35800.0547
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31546.8047 - val_loss: 33241.8047
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30555.9941 - val_loss: 39319.3633
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32058.2266 - val_loss: 33373.0312
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31084.6133 - val_loss: 31928.0391
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31780.8691 - val_loss: 28700.7324
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32901.8047 - val_loss: 39975.4102
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29870.6875 - val_loss: 39492.2734
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30348.2754 - val_loss: 35891.5234
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30142.9336 - val_loss: 37651.0508
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 32907.7031 - val_loss: 38629.9336
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 30038.7676 - val_loss: 40903.5742
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 31311.4219 - val_loss: 27581.0977
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 31956.4316 - val_loss: 35806.3438
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 30338.1973 - val_loss: 39733.9414
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 31478.2129 - val_loss: 36576.2695
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 30737.1953 - val_loss: 36082.5391
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 32179.7832 - val_loss: 37734.6016
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 30264.7402 - val_loss: 35378.9727
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 30406.8359 - val_loss: 34917.3438
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 30942.4238 - val_loss: 41982.5898
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 31391.7344 - val_loss: 37819.9414
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 33369.7031 - val_loss: 29469.9863
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 30406.7168 - val_loss: 37341.2031
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 30874.6074 - val_loss: 37446.5703
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 31663.0098 - val_loss: 36480.4688
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 33084.9297 - val_loss: 36816.8906
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32831.6836 - val_loss: 30857.7090
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29769.8320 - val_loss: 30354.5156
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30677.3809 - val_loss: 34857.5430
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 29985.7285 - val_loss: 39794.9336
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29635.1172 - val_loss: 32244.5977
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32776.7891 - val_loss: 33147.2031
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31500.5820 - val_loss: 33682.3516
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30037.7441 - val_loss: 37554.6016
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30669.3398 - val_loss: 36245.9141
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30992.5449 - val_loss: 40025.5312

In [ ]:
preds = model.predict(X_valid)

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
print(f'MAE: {mean_absolute_error(preds, y_valid)}')

MAE: 176695.234375